name: Release Wheel

on: workflow_dispatch
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --wheel
          --outdir dist/
          .
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
